name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.12
  file_picker: ^5.2.3
  flutter_lints: ^5.0.0
  flutter_neumorphic: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/chair1.png
    - assets/bg.png
