name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  flutter_lints: ^5.0.0
  flutter_neumorphic: ^3.2.0
  universal_html: ^2.2.4
  permission_handler: ^11.0.1
  gif_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/chair.png
    - assets/chair2.png
    - assets/config.json
    - assets/bladder.gif
    - assets/bladder_static.png
    - assets/logo.png
